site_name: Fente technical documentation
docs_dir: docs
theme:
  name: readthedocs
extra_css:
  - css/customstyle.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - admonition
  - pymdownx.details